### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by ghost** [fuzzysteve/CREST-Market-Downloader#6]
File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "C:\Python27\lib\site-packages\grequests.py", line 71, in send
    self.url, *_merged_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, *_send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.'))
<Greenlet at 0x7ce2f30: <bound method AsyncRequest.send of <grequests.AsyncRequest object at 0x07CD7830>>(stream=False)> failed with ConnectionError

Traceback (most recent call last):
  File "X:\downloader.py", line 148, in get_region
    buy=self.get_multiple_endpoint(buyUrls, 'application/vnd.ccp.eve.MarketOrderCollection-v1+json; charset=utf-8')
  File "X:\downloader.py", line 181, in get_multiple_endpoint
    add=response.json()
AttributeError: 'NoneType' object has no attribute 'json'

**Comment by fuzzysteve** [comment]
hrm. That _sounds_ like a problem between you and CCP.
